name: benchmarks CUDA

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - '**'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
    - uses: Jimver/cuda-toolkit@v0.2.11
      id: cuda-toolkit
      with:
        method: network
        sub-packages: '["nvcc","cudart"]'
        cuda: '12.1.0'
    - run: |
        echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}" && echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}" && nvcc -V

    - uses: actions/checkout@v3
    - run: |
        make
        ./benchsys -b gpu
